/*
 * syscall_table.c — x86-64 Linux syscall name table
 *
 * Covers the most common syscalls (~110 entries). Unknown numbers
 * return NULL; the caller (reporter) renders them as "syscall_<nr>".
 *
 * Reference: arch/x86/entry/syscalls/syscall_64.tbl in the Linux kernel.
 */

#include "syscall_table.h"
#include <stddef.h>

/* Direct-indexed table. NULL slots = either unimplemented or
 * outside the common subset; reporter handles them. */
#define MAX_SYSCALL 335

static const char *table[MAX_SYSCALL] = {
    [0]   = "read",
    [1]   = "write",
    [2]   = "open",
    [3]   = "close",
    [4]   = "stat",
    [5]   = "fstat",
    [6]   = "lstat",
    [7]   = "poll",
    [8]   = "lseek",
    [9]   = "mmap",
    [10]  = "mprotect",
    [11]  = "munmap",
    [12]  = "brk",
    [13]  = "rt_sigaction",
    [14]  = "rt_sigprocmask",
    [15]  = "rt_sigreturn",
    [16]  = "ioctl",
    [17]  = "pread64",
    [18]  = "pwrite64",
    [19]  = "readv",
    [20]  = "writev",
    [21]  = "access",
    [22]  = "pipe",
    [23]  = "select",
    [24]  = "sched_yield",
    [25]  = "mremap",
    [28]  = "madvise",
    [32]  = "dup",
    [33]  = "dup2",
    [35]  = "nanosleep",
    [39]  = "getpid",
    [41]  = "socket",
    [42]  = "connect",
    [43]  = "accept",
    [44]  = "sendto",
    [45]  = "recvfrom",
    [46]  = "sendmsg",
    [47]  = "recvmsg",
    [48]  = "shutdown",
    [49]  = "bind",
    [50]  = "listen",
    [51]  = "getsockname",
    [52]  = "getpeername",
    [54]  = "setsockopt",
    [55]  = "getsockopt",
    [56]  = "clone",
    [57]  = "fork",
    [58]  = "vfork",
    [59]  = "execve",
    [60]  = "exit",
    [61]  = "wait4",
    [62]  = "kill",
    [63]  = "uname",
    [72]  = "fcntl",
    [73]  = "flock",
    [74]  = "fsync",
    [78]  = "getdents",
    [79]  = "getcwd",
    [80]  = "chdir",
    [82]  = "rename",
    [83]  = "mkdir",
    [84]  = "rmdir",
    [85]  = "creat",
    [86]  = "link",
    [87]  = "unlink",
    [88]  = "symlink",
    [89]  = "readlink",
    [90]  = "chmod",
    [92]  = "chown",
    [95]  = "umask",
    [96]  = "gettimeofday",
    [97]  = "getrlimit",
    [98]  = "getrusage",
    [99]  = "sysinfo",
    [102] = "getuid",
    [104] = "getgid",
    [107] = "geteuid",
    [108] = "getegid",
    [110] = "getppid",
    [158] = "arch_prctl",
    [186] = "gettid",
    [202] = "futex",
    [217] = "getdents64",
    [218] = "set_tid_address",
    [228] = "clock_gettime",
    [231] = "exit_group",
    [232] = "epoll_wait",
    [233] = "epoll_ctl",
    [257] = "openat",
    [258] = "mkdirat",
    [259] = "mknodat",
    [260] = "fchownat",
    [262] = "newfstatat",
    [263] = "unlinkat",
    [264] = "renameat",
    [267] = "readlinkat",
    [268] = "fchmodat",
    [269] = "faccessat",
    [273] = "set_robust_list",
    [281] = "epoll_pwait",
    [288] = "accept4",
    [291] = "epoll_create1",
    [292] = "dup3",
    [293] = "pipe2",
    [302] = "prlimit64",
    [318] = "getrandom",
    [319] = "memfd_create",
    [332] = "statx",
    [334] = "rseq",
};

const char *syscall_name(long nr) {
    if (nr < 0 || nr >= MAX_SYSCALL) return NULL;
    return table[nr];
}